'use client';

import { useState } from 'react';
import { Plus, Trash2, Play, Download, Loader2, ChevronLeft, ChevronRight, Maximize, Eye } from 'lucide-react';
import { cn } from '@/lib/utils';

interface PresentationToolProps {
  locale: string;
  messages: Record<string, unknown>;
}

interface Slide {
  id: number;
  type: 'title' | 'content' | 'twoColumn' | 'quote';
  title: string;
  content: string;
  notes: string;
}

export function PresentationTool({ locale, messages }: PresentationToolProps) {
  const t = (messages.tools as Record<string, Record<string, unknown>>).presentation as Record<string, unknown>;
  const templateNames = (t.templateNames || {}) as Record<string, string>;
  const slideTypes = (t.slideTypes || {}) as Record<string, string>;
  const downloadFormats = (t.downloadFormats || {}) as Record<string, string>;
  const isRtl = locale === 'ar';

  const [selectedTemplate, setSelectedTemplate] = useState('business');
  const [slides, setSlides] = useState<Slide[]>([
    { id: 1, type: 'title', title: 'Presentation Title', content: 'Subtitle or description', notes: '' },
    { id: 2, type: 'content', title: 'Key Points', content: '• First point\n• Second point\n• Third point', notes: '' },
  ]);
  const [activeSlide, setActiveSlide] = useState(0);
  const [isPresenting, setIsPresenting] = useState(false);
  const [isGenerating, setIsGenerating] = useState(false);
  const [outlinePrompt, setOutlinePrompt] = useState('');
  const [showOutline, setShowOutline] = useState(true);

  const addSlide = (type: Slide['type']) => {
    const newSlide: Slide = {
      id: Date.now(),
      type,
      title: '',
      content: '',
      notes: '',
    };
    setSlides([...slides, newSlide]);
    setActiveSlide(slides.length);
  };

  const updateSlide = (id: number, field: keyof Slide, value: string) => {
    setSlides(slides.map(slide =>
      slide.id === id ? { ...slide, [field]: value } : slide
    ));
  };

  const deleteSlide = (id: number) => {
    if (slides.length <= 1) return;
    setSlides(slides.filter(slide => slide.id !== id));
    if (activeSlide >= slides.length - 1) {
      setActiveSlide(Math.max(0, slides.length - 2));
    }
  };

  const handleGenerateOutline = async () => {
    if (!outlinePrompt.trim()) return;
    setIsGenerating(true);
    await new Promise(resolve => setTimeout(resolve, 2000));

    const generatedSlides: Slide[] = [
      { id: 1, type: 'title', title: outlinePrompt || 'Presentation Title', content: 'Generated by AI', notes: '' },
      { id: 2, type: 'content', title: 'Introduction', content: '• Overview of the topic\n• Background information\n• Current state', notes: 'Introduce the main topic' },
      { id: 3, type: 'twoColumn', title: 'Key Features', content: 'Left: Feature A\nRight: Feature B', notes: '' },
      { id: 4, type: 'content', title: 'Benefits', content: '• Benefit 1\n• Benefit 2\n• Benefit 3', notes: '' },
      { id: 5, type: 'quote', title: '', content: '"The best way to predict the future is to create it."', notes: '' },
      { id: 6, type: 'content', title: 'Next Steps', content: '• Action item 1\n• Action item 2\n• Timeline', notes: '' },
      { id: 7, type: 'title', title: 'Thank You', content: 'Questions?', notes: '' },
    ];

    setSlides(generatedSlides);
    setIsGenerating(false);
    setShowOutline(false);
  };

  const currentSlide = slides[activeSlide];

  return (
    <div className="grid gap-6 lg:grid-cols-4">
      {/* Sidebar - Slide List */}
      <div className="space-y-4">
        {/* Templates */}
        <div className="rounded-xl border border-n-200 bg-white p-4">
          <h4 className="mb-3 text-sm font-medium text-n-700">{t.templates as string}</h4>
          <div className="grid grid-cols-2 gap-2">
            {Object.entries(templateNames).map(([key, label]) => (
              <button
                key={key}
                onClick={() => setSelectedTemplate(key)}
                className={cn(
                  'rounded-lg border px-2 py-1.5 text-xs font-medium transition-all',
                  selectedTemplate === key
                    ? 'border-accent bg-accent text-white'
                    : 'border-n-200 text-n-700 hover:border-n-300'
                )}
              >
                {label}
              </button>
            ))}
          </div>
        </div>

        {/* Slide List */}
        <div className="rounded-xl border border-n-200 bg-white p-4">
          <div className="mb-3 flex items-center justify-between">
            <h4 className="text-sm font-medium text-n-700">{t.slides as string}</h4>
            <span className="text-xs text-n-500">{slides.length} {t.slideCount as string}</span>
          </div>
          <div className="space-y-2 max-h-[300px] overflow-y-auto">
            {slides.map((slide, index) => (
              <div
                key={slide.id}
                onClick={() => setActiveSlide(index)}
                className={cn(
                  'flex items-center gap-2 rounded-lg border p-2 cursor-pointer transition-all',
                  activeSlide === index
                    ? 'border-accent bg-accent/5'
                    : 'border-n-200 hover:border-n-300'
                )}
              >
                <span className="flex h-6 w-6 flex-shrink-0 items-center justify-center rounded bg-n-100 text-xs font-medium text-n-600">
                  {index + 1}
                </span>
                <span className="flex-1 truncate text-sm text-n-700">
                  {slide.title || slideTypes[slide.type]}
                </span>
                <button
                  onClick={(e) => { e.stopPropagation(); deleteSlide(slide.id); }}
                  className="text-n-400 hover:text-error"
                >
                  <Trash2 className="h-3 w-3" />
                </button>
              </div>
            ))}
          </div>
          <div className="mt-3 flex flex-wrap gap-1">
            {Object.entries(slideTypes).slice(0, 4).map(([key, label]) => (
              <button
                key={key}
                onClick={() => addSlide(key as Slide['type'])}
                className="flex items-center gap-1 rounded-lg border border-n-200 px-2 py-1 text-xs text-n-600 hover:border-accent hover:bg-accent/5"
              >
                <Plus className="h-3 w-3" />
                {label}
              </button>
            ))}
          </div>
        </div>

        {/* Actions */}
        <div className="space-y-2">
          <button
            onClick={() => setIsPresenting(true)}
            className="flex w-full items-center justify-center gap-2 rounded-xl bg-accent py-2.5 text-sm font-semibold text-white hover:bg-accent/90"
          >
            <Play className="h-4 w-4" />
            {t.present as string}
          </button>
          <button className="flex w-full items-center justify-center gap-2 rounded-xl border border-n-200 py-2.5 text-sm font-medium text-n-700 hover:bg-n-100">
            <Download className="h-4 w-4" />
            {t.download as string}
          </button>
        </div>
      </div>

      {/* Main Editor Area */}
      <div className="lg:col-span-3 space-y-6">
        {/* Outline Generator */}
        {showOutline && (
          <div className="rounded-xl border border-accent/20 bg-accent/5 p-4">
            <h4 className="mb-2 font-medium text-n-900">{t.outline as string}</h4>
            <div className="flex gap-2">
              <input
                type="text"
                value={outlinePrompt}
                onChange={(e) => setOutlinePrompt(e.target.value)}
                placeholder={t.outlinePlaceholder as string}
                className="flex-1 rounded-lg border border-n-200 bg-white px-3 py-2 text-sm focus:border-accent focus:outline-none"
              />
              <button
                onClick={handleGenerateOutline}
                disabled={!outlinePrompt.trim() || isGenerating}
                className={cn(
                  'flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all',
                  outlinePrompt.trim() && !isGenerating
                    ? 'bg-accent text-white hover:bg-accent/90'
                    : 'bg-n-200 text-n-500 cursor-not-allowed'
                )}
              >
                {isGenerating ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                {t.generateOutline as string}
              </button>
            </div>
          </div>
        )}

        {/* Preview Area */}
        <div className="rounded-xl border border-n-200 bg-white">
          <div className="aspect-video bg-gradient-to-br from-n-100 to-n-200 p-8 flex items-center justify-center">
            {currentSlide && (
              <div className={cn(
                'w-full max-w-2xl rounded-lg bg-white p-8 shadow-lg',
                currentSlide.type === 'title' && 'text-center'
              )}>
                {currentSlide.type === 'title' ? (
                  <>
                    <h1 className="mb-4 text-3xl font-bold text-n-900">{currentSlide.title}</h1>
                    <p className="text-lg text-n-600">{currentSlide.content}</p>
                  </>
                ) : currentSlide.type === 'quote' ? (
                  <div className="text-center">
                    <p className="mb-4 text-2xl italic text-n-700">{currentSlide.content}</p>
                  </div>
                ) : currentSlide.type === 'twoColumn' ? (
                  <div>
                    <h2 className="mb-4 text-xl font-bold text-n-900">{currentSlide.title}</h2>
                    <div className="grid grid-cols-2 gap-4">
                      <div className="rounded-lg bg-n-50 p-4">
                        <p className="whitespace-pre-wrap text-sm text-n-700">{currentSlide.content.split('\n')[0]}</p>
                      </div>
                      <div className="rounded-lg bg-n-50 p-4">
                        <p className="whitespace-pre-wrap text-sm text-n-700">{currentSlide.content.split('\n')[1]}</p>
                      </div>
                    </div>
                  </div>
                ) : (
                  <div>
                    <h2 className="mb-4 text-xl font-bold text-n-900">{currentSlide.title}</h2>
                    <p className="whitespace-pre-wrap text-n-700">{currentSlide.content}</p>
                  </div>
                )}
              </div>
            )}
          </div>
          
          {/* Navigation */}
          <div className="flex items-center justify-between border-t border-n-200 px-4 py-3">
            <button
              onClick={() => setActiveSlide(Math.max(0, activeSlide - 1))}
              disabled={activeSlide === 0}
              className="flex items-center gap-1 text-sm text-n-600 hover:text-n-900 disabled:opacity-50"
            >
              <ChevronLeft className="h-4 w-4" />
              Previous
            </button>
            <span className="text-sm text-n-500">
              {activeSlide + 1} / {slides.length}
            </span>
            <button
              onClick={() => setActiveSlide(Math.min(slides.length - 1, activeSlide + 1))}
              disabled={activeSlide === slides.length - 1}
              className="flex items-center gap-1 text-sm text-n-600 hover:text-n-900 disabled:opacity-50"
            >
              Next
              <ChevronRight className="h-4 w-4" />
            </button>
          </div>
        </div>

        {/* Slide Editor */}
        <div className="rounded-xl border border-n-200 bg-white p-6">
          <h3 className="mb-4 font-semibold text-n-900">
            {locale === 'ar' ? 'تحرير الشريحة' : 'Edit Slide'}
          </h3>
          <div className="space-y-4">
            <div>
              <label className="mb-1.5 block text-sm font-medium text-n-700">
                {(t.editor as Record<string, string>).title}
              </label>
              <input
                type="text"
                value={currentSlide?.title || ''}
                onChange={(e) => currentSlide && updateSlide(currentSlide.id, 'title', e.target.value)}
                placeholder={(t.editor as Record<string, string>).titlePlaceholder}
                className="w-full rounded-lg border border-n-200 px-3 py-2.5 text-sm text-n-900 focus:border-accent focus:outline-none"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-medium text-n-700">
                {(t.editor as Record<string, string>).content}
              </label>
              <textarea
                value={currentSlide?.content || ''}
                onChange={(e) => currentSlide && updateSlide(currentSlide.id, 'content', e.target.value)}
                placeholder={(t.editor as Record<string, string>).contentPlaceholder}
                rows={4}
                className="w-full rounded-lg border border-n-200 px-3 py-2.5 text-sm text-n-900 focus:border-accent focus:outline-none"
              />
            </div>
            <div>
              <label className="mb-1.5 block text-sm font-medium text-n-700">
                {(t.editor as Record<string, string>).notes}
              </label>
              <textarea
                value={currentSlide?.notes || ''}
                onChange={(e) => currentSlide && updateSlide(currentSlide.id, 'notes', e.target.value)}
                placeholder={(t.editor as Record<string, string>).notesPlaceholder}
                rows={2}
                className="w-full rounded-lg border border-n-200 px-3 py-2.5 text-sm text-n-900 focus:border-accent focus:outline-none"
              />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
